apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openplc-workdir
  namespace: openplc
  labels:
    app: openplc-runtime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
