apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-data
  namespace: ignition
  labels:
    app: ignition
    component: gateway-primary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
